"""API dependencies."""

from app.core.dependencies import (
    CurrentUser,
    DatabaseSession,
    OptionalUser,
    RequireAdmin,
    RequireApartmentManager,
    RequireDoctor,
    RequireHotelManager,
    RequirePatient,
    RequireRestaurantManager,
    RequireSuperAdmin,
    SuperUser,
    get_current_active_superuser,
    get_current_patient,
    get_current_user,
    get_current_user_optional,
    get_db,
    require_roles,
)

__all__ = [
    "CurrentUser",
    "DatabaseSession",
    "OptionalUser",
    "RequireAdmin",
    "RequireApartmentManager",
    "RequireDoctor",
    "RequireHotelManager",
    "RequirePatient",
    "RequireRestaurantManager",
    "RequireSuperAdmin",
    "SuperUser",
    "get_current_active_superuser",
    "get_current_patient",
    "get_current_user",
    "get_current_user_optional",
    "get_db",
    "require_roles",
]
