"""add_doctor_primary_specialty_and_make_room_name_optional

Revision ID: 0701fa325cae
Revises: a2b3c4d5e6f7
Create Date: 2026-04-06 00:07:14.265735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0701fa325cae'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('doctors', sa.Column('primary_specialty', sa.String(length=100), nullable=True))
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('hotels', 'nearby_transport',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('hotels', 'nearby_restaurants',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('doctors', 'primary_specialty')
    # ### end Alembic commands ###
