"""update_room_view_to_jsonb_and_add_hotel_facilities

Revision ID: 1ac138c6d39d
Revises: b27a85a95232
Create Date: 2026-04-08 00:14:15.521224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ac138c6d39d'
down_revision: Union[str, None] = 'b27a85a95232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_is_deleted'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_conditions_is_deleted'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_patient_id'), table_name='medical_conditions')
    op.drop_table('medical_conditions')
    op.drop_index(op.f('ix_allergies_is_deleted'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    op.drop_table('allergies')
    op.add_column('hotels', sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('rooms', 'view',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(view)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'view',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('hotels', 'facilities')
    op.create_table('allergies',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allergen', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('diagnosed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('allergies_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('allergies_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('allergies_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('allergies_pkey'))
    )
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_allergies_is_deleted'), 'allergies', ['is_deleted'], unique=False)
    op.create_table('medical_conditions',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('condition_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('diagnosed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('medical_conditions_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medical_conditions_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('medical_conditions_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_conditions_pkey'))
    )
    op.create_index(op.f('ix_medical_conditions_patient_id'), 'medical_conditions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_conditions_is_deleted'), 'medical_conditions', ['is_deleted'], unique=False)
    op.create_table('medications',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prescribing_doctor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('medications_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medications_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('medications_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('medications_pkey'))
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_is_deleted'), 'medications', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
