"""add_hero_sliders_table

Revision ID: 2a775df5ee3e
Revises: k5l6m7n8o9p0
Create Date: 2026-04-12 01:37:54.745054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a775df5ee3e'
down_revision: Union[str, None] = 'k5l6m7n8o9p0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_sliders',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_image', sa.String(length=500), nullable=True),
    sa.Column('badge_text', sa.String(length=100), nullable=True),
    sa.Column('primary_cta_text', sa.String(length=100), nullable=True),
    sa.Column('primary_cta_url', sa.String(length=500), nullable=True),
    sa.Column('secondary_cta_text', sa.String(length=100), nullable=True),
    sa.Column('secondary_cta_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_sliders_is_deleted'), 'hero_sliders', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_medical_conditions_is_deleted'), table_name='medical_conditions')
    op.drop_index(op.f('ix_medical_conditions_patient_id'), table_name='medical_conditions')
    op.drop_table('medical_conditions')
    op.drop_index(op.f('ix_medications_is_deleted'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_allergies_is_deleted'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    op.drop_table('allergies')
    op.create_index(op.f('ix_dining_pass_purchases_is_deleted'), 'dining_pass_purchases', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'dining_pass_purchases', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dining_pass_purchases', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_dining_passes_is_deleted'), 'dining_passes', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'dining_passes', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dining_passes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dining_passes', type_='foreignkey')
    op.drop_constraint(None, 'dining_passes', type_='foreignkey')
    op.drop_index(op.f('ix_dining_passes_is_deleted'), table_name='dining_passes')
    op.drop_constraint(None, 'dining_pass_purchases', type_='foreignkey')
    op.drop_constraint(None, 'dining_pass_purchases', type_='foreignkey')
    op.drop_index(op.f('ix_dining_pass_purchases_is_deleted'), table_name='dining_pass_purchases')
    op.create_table('allergies',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allergen', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('diagnosed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('allergies_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('allergies_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('allergies_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('allergies_pkey'))
    )
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_allergies_is_deleted'), 'allergies', ['is_deleted'], unique=False)
    op.create_table('medications',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prescribing_doctor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('medications_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medications_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('medications_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('medications_pkey'))
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_is_deleted'), 'medications', ['is_deleted'], unique=False)
    op.create_table('medical_conditions',
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('condition_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('diagnosed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('medical_conditions_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medical_conditions_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('medical_conditions_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_conditions_pkey'))
    )
    op.create_index(op.f('ix_medical_conditions_patient_id'), 'medical_conditions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_conditions_is_deleted'), 'medical_conditions', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_hero_sliders_is_deleted'), table_name='hero_sliders')
    op.drop_table('hero_sliders')
    # ### end Alembic commands ###
