"""Add break times

Revision ID: 9b19ef92677a
Revises: 
Create Date: 2026-01-31 23:27:37.986372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b19ef92677a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_availability', sa.Column('break_start_time', sa.Time(), nullable=True))
    op.add_column('doctor_availability', sa.Column('break_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_availability', 'break_end_time')
    op.drop_column('doctor_availability', 'break_start_time')
    # ### end Alembic commands ###
